language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

branches:
  only:
    - master

install:
  - pip install coveralls nox

script: nox --session "test"

after_success:
  - coveralls

notifications:
  email: false
